// Auto-generated reference enrichment data for resale PDF parser.
// Source: reference app properties.json (app-revenda-red.vercel.app)
// Maps RQB codes to known URLs, regions, and addresses that are NOT present in the PDF.
// Used to enrich PDF-extracted data after parsing.

export interface ResaleReferenceEntry {
  url: string;
  region: string;
  address: string;
}

export const RESALE_REFERENCE_MAP: Record<string, ResaleReferenceEntry> = {
  'RQB0490': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-sul-aguas-claras-df-avenida-pau-brasil-1173383', region: '\u00c1GUAS CLARAS', address: 'Avenida Pau Brasil, LT 12' },
  'RQB0595': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-4-quartos-venda-taguatinga-norte-taguatinga-df-cnb-3-1240689', region: 'TAGUATINGA', address: 'CNB QD 3 LT 12' },
  'RQB0609': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-asa-sul-brasilia-df-sqs-107-bloco-a-1252185', region: 'ASA SUL', address: 'SQS 107, Bloco A' },
  'RQB0624': { url: 'https://www.dfimoveis.com.br/imovel/loja-0-quartos-venda-norte-aguas-claras-df-avenida-parque-guas-claras-1269651', region: '\u00c1GUAS CLARAS', address: 'Rua 33 Sul' },
  'RQB0627': { url: 'https://www.wimoveis.com.br/propriedades/loja-comercial-no-le-club-aguas-claras-82-m-2-3024211118.html', region: '\u00c1GUAS CLARAS', address: 'Rua 33 Sul' },
  'RQB0630': { url: 'https://www.dfimoveis.com.br/imovel/loja-0-quartos-venda-sig-brasilia-df-sig-quadra-6-1283748', region: 'SUDOESTE', address: 'Quadra SIG Quadra 6, 14' },
  'RQB0639': { url: 'https://www.wimoveis.com.br/propriedades/cobertura-4-suites-lazer-privativo-4-vagas-vista-3025770863.html', region: '\u00c1GUAS CLARAS', address: 'Quadra 205, 1902' },
  'RQB0644': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-3-quartos-no-sudoeste-3026749584.html', region: 'SUDOESTE', address: 'Quadra CLSW 300A Bloco 3, 88' },
  'RQB0649': { url: 'https://www.wimoveis.com.br/propriedades/casa-de-2-quartos-no-jardim-europa-i-grande-colorado-3028238851.html', region: 'SOBRADINHO', address: 'Rodovia DF-150 QD 2 Conj D casa 03' },
  'RQB0652': { url: 'https://www.wimoveis.com.br/propriedades/casa-de-4-quartos-na-colonia-agricola-aguas-claras-3029969729.html', region: 'GUAR\u00c1 I E II', address: 'Col\u00f4nia Agr\u00edcola \u00c1guas Claras Ch\u00e1cara 18, lote 12' },
  'RQB0656': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-1-quarto-suite-no-sudoeste-3029234870.html', region: 'SUDOESTE', address: 'Quadra CCSW 5 Lote 1 Bloco A, 204' },
  'RQB0658': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-2-quartos-com-suite-em-sobradinho-3031794322.html', region: 'SOBRADINHO', address: 'Quadra 02 Conjunto B' },
  'RQB0659': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-asa-norte-brasilia-df-sqn-312-bloco-c-1330561', region: 'ASA NORTE', address: 'Quadra SQN 312 Bloco C, 104' },
  'RQB0662': { url: 'https://www.dfimoveis.com.br/propriedades/venice-park-sul-1-quarto-mobiliado-pronto-para-morar-3030724703.html', region: 'PARK SUL', address: 'Setor SGCV, Park Sul Lt 10' },
  'RQB0665': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-5-quartos-venda-jardim-botanico-brasilia-df-condomnio-residencial-jardins-do-lago-1330482', region: 'JARDIM BOT\u00c2NICO', address: 'Condom\u00ednio Residencial Jardins do Lago, 12, CASA' },
  'RQB0674': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-norte-aguas-claras-df-rua-30-1331785', region: '\u00c1GUAS CLARAS', address: 'Rua 30, 3' },
  'RQB0675': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-3-quartos-com-1-suite-em-sobradinho-3032876201.html', region: 'SOBRADINHO', address: 'Quadra 02 Conjunto B' },
  'RQB0676': { url: 'https://www.dfimoveis.com.br/imovel/lote-0-quartos-venda-saan-setor-industrial-df-saan-quadra-2-1331932', region: 'SAAN', address: 'Quadra SAAN Quadra 2 905 A 935' },
  'RQB0697': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-sul-aguas-claras-df-rua-copaiba-1349646', region: '\u00c1GUAS CLARAS', address: 'Rua Copa\u00edba LOTE 9 BLOCO C, 1106' },
  'RQB0701': { url: 'https://www.dfimoveis.com.br/imovel/hotel-flat-1-quarto-venda-asa-norte-brasilia-df-shn-quadra-1-1359000', region: 'ASA NORTE', address: 'Quadra SHN Quadra 1, 317' },
  'RQB0702': { url: '', region: 'SUDOESTE', address: 'Quadra SQSW 305 Bloco I, 607' },
  'RQB0703': { url: 'https://www.wimoveis.com.br/propriedades/casa-de-4-suites-no-condominio-baviera-em-vicente-3038639397.html', region: 'VICENTE PIRES', address: 'Rua 10 Ch\u00e1cara 164 24' },
  'RQB0705': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-3-quartos-sendo-1-suite-em-aguas-claras-3036723454.html', region: '\u00c1GUAS CLARAS', address: 'Rua 35, 402' },
  'RQB0706': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-2-quartos-sendo-1-suite-no-guara-ii-3036339559.html', region: 'GUAR\u00c1 I E II', address: '\u00c1rea Especial 4 Lotes E/F, 1503' },
  'RQB0707': { url: 'https://www.wimoveis.com.br/propriedades/casa-com-4-quartos-sendo-3-suites-em-lote-de-800m-na-3040152695.html', region: 'VICENTE PIRES', address: 'Quadra 3 Conjunto 12' },
  'RQB0708': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-alto-padrao-com-2-suites-e-2-vagas-no-3040205374.html', region: 'PARK SUL', address: 'Setor SGCV, Zona Industrial' },
  'RQB0709': { url: 'https://www.wimoveis.com.br/propriedades/casa-de-alto-padrao-com-4-suites-area-gourmet-e-3040131623.html', region: 'VICENTE PIRES', address: 'Rua 4' },
  'RQB0710': { url: 'https://www.dfimoveis.com.br/imovel/casa-3-quartos-venda-vicente-pires-vicente-pires-df-rua-4-1400554', region: 'VICENTE PIRES', address: 'Rua 4' },
  'RQB0711': { url: 'https://www.dfimoveis.com.br/imovel/casa-3-quartos-venda-vicente-pires-vicente-pires-df-rua-4-1399971', region: 'VICENTE PIRES', address: 'Rua 4' },
  'RQB0714': { url: 'https://www.dfimoveis.com.br/imovel/lote-0-quartos-venda-vicente-pires-vicente-pires-df-rua-4a-rea-feira-1398902', region: 'VICENTE PIRES', address: 'Rua 4A \u00c1rea Feira Feira do Produtor' },
  'RQB0715': { url: '', region: '\u00c1GUAS CLARAS', address: 'Avenida Pau Brasil' },
  'RQB0716': { url: 'https://www.wimoveis.com.br/propriedades/sqs-316-asa-sul-4-quartos-nascente-com-garagem-3038037751.html', region: 'ASA SUL', address: 'Quadra SQS 316 Bloco' },
  'RQB0719': { url: 'https://www.wimoveis.com.br/propriedades/casa-de-2-quartos-em-condominio-no-setor-habitacional-3038489762.html', region: '\u00c1GUAS CLARAS', address: 'Conjunto SHA Conjunto 3 Ch\u00e1cara 41 12 A' },
  'RQB0721': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-3-quartos-venda-sobradinho-sobradinho-df-condomnio-colina-nova-diguinea-1411290', region: 'SOBRADINHO', address: 'Condom\u00ednio Colina Nova Diguinea' },
  'RQB0722': { url: 'https://www.dfimoveis.com.br/imovel/casa-3-quartos-venda-arniqueira-aguas-claras-df-sha-conjunto-5-chacar-47-1375404', region: '\u00c1GUAS CLARAS', address: 'Conjunto SHA Conjunto 5 Ch\u00e1cara 47' },
  'RQB0723': { url: 'https://www.dfimoveis.com.br/imovel/lote-0-quartos-venda-guara-i-guara-df-agrcola-guas-claras-chacar-71-1380148', region: 'GUAR\u00c1 I E II', address: 'Col\u00f4nia Agr\u00edcola \u00c1guas Claras Ch\u00e1cara 71' },
  'RQB0726': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-de-3-quartos-sendo-1-suite-no-quattre-3038403286.html', region: 'SOBRADINHO', address: 'Quadra 2 Conjunto B-8 302' },
  'RQB0727': { url: 'https://www.wimoveis.com.br/propriedades/apartamento-para-venda-com-2-quartos-em-asa-norte-com-3038200576.html', region: 'ASA NORTE', address: 'Setor SHTN Trecho 2 Lote 3' },
  'RQB0734': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-taguatinga-sul-taguatinga-df-csg-3-1380138', region: 'TAGUATINGA', address: 'Quadra CSG 3' },
  'RQB0735': { url: 'https://www.dfimoveis.com.br/imovel/casa-2-quartos-venda-vicente-pires-vicente-pires-df-rua-6-chacar-250-1375431', region: 'VICENTE PIRES', address: 'Rua 6 Ch\u00e1cara 250 33' },
  'RQB0736': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-norte-aguas-claras-df-rua-das-paineiras-1380130', region: '\u00c1GUAS CLARAS', address: 'Rua das Paineira' },
  'RQB0737': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-noroeste-brasilia-df-sqnw-302-bloco-h-1375475', region: 'NOROESTE', address: 'Quadra SQNW 302 Bloco H 110' },
  'RQB0738': { url: 'https://www.wimoveis.com.br/propriedades/square-garden-aguas-claras-apartamento-de-3-quartos-3038396315.html', region: '\u00c1GUAS CLARAS', address: 'Rua 27 1206' },
  'RQB0739': { url: 'https://www.wimoveis.com.br/propriedades/golden-office-sala-comercial-na-asa-norte-3038397463.html', region: 'ASA NORTE', address: 'Quadra SGAN 915 M\u00f3dulo G 207' },
  'RQB0740': { url: 'https://www.wimoveis.com.br/propriedades/brisas-do-lago-apartamento-de-1-quarto-suite-na-asa-3038490932.html', region: 'ASA SUL', address: 'Trecho SCES Trecho 4 108' },
  'RQB0741': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-norte-aguas-claras-df-rua-das-carnaubas-1383041', region: '\u00c1GUAS CLARAS', address: 'Rua das Carna\u00fabas 807' },
  'RQB0745': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-sul-aguas-claras-df-rua-copaiba-1377386', region: '\u00c1GUAS CLARAS', address: 'Rua Copa\u00edba, Lote 9 Bloco C Apt 1006' },
  'RQB0746': { url: 'https://www.dfimoveis.com.br/imovel/casa-3-quartos-venda-arniqueira-aguas-claras-df-sha-conjunto-3-chacar-45-1377013', region: '\u00c1GUAS CLARAS', address: 'Conjunto SHA Conjunto 3 Ch\u00e1cara 45' },
  'RQB0748': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-sul-aguas-claras-df-quadra-208-1376877', region: '\u00c1GUAS CLARAS', address: 'Quadra 208, Sul' },
  'RQB0749': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-sul-aguas-claras-df-quadra-208-1376575', region: '\u00c1GUAS CLARAS', address: 'Quadra 208, Sul' },
  'RQB0750': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-norte-aguas-claras-df-rua-13-1398899', region: '\u00c1GUAS CLARAS', address: 'Rua 13, Norte' },
  'RQB0752': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-park-sul-brasilia-df-sgcv-1397690', region: 'PARK SUL', address: 'Setor SGCV, Zona Industrial' },
  'RQB0753': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-samambaia-norte-samambaia-df-qn-406-conjunto-e-1397713', region: 'SAMAMBAIA', address: 'Quadra QN 406 Conjunto E Com\u00e9rcio lote 01, apt 204' },
  'RQB0755': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-3-quartos-venda-park-way-brasilia-df-smpw-quadra-17-conjunto-12-1397780', region: 'PARK WAY', address: 'Quadra SMPW Quadra 17 Conjunto 12 07, CASA H' },
  'RQB0756': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-taguatinga-norte-taguatinga-df-qnl-6-bloco-c-1385152', region: 'TAGUATINGA', address: 'Quadra QNL 6 Bloco C' },
  'RQB0757': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-areal-aguas-claras-df-qs-9-rua-100-1385193', region: '\u00c1GUAS CLARAS', address: 'Quadra QS 9 Rua 100 , Areal' },
  'RQB0758': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-setor-industrial-taguatinga-df-qi-24-1385183', region: 'TAGUATINGA', address: 'Quadra QI 24' },
  'RQB0761': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-norte-aguas-claras-df-rua-20-1385137', region: '\u00c1GUAS CLARAS', address: 'Rua 20, Norte' },
  'RQB0763': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-4-quartos-venda-sudoeste-brasilia-df-sqsw-500-1385034', region: 'SUDOESTE', address: 'Quadra SQSW 500' },
  'RQB0766': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-norte-aguas-claras-df-alameda-das-accias-quadra-107-1399958', region: '\u00c1GUAS CLARAS', address: 'Alameda das Ac\u00e1cias Quadra 107' },
  'RQB0767': { url: 'https://www.dfimoveis.com.br/imovel/sala-0-quartos-venda-norte-aguas-claras-df-avenida-pau-brasil-1400560', region: '\u00c1GUAS CLARAS', address: 'Avenida Pau Brasil' },
  'RQB0770': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-taguatinga-centro-taguatinga-df-quadra-c-5-1406657', region: 'TAGUATINGA', address: 'Central Quadra 5 Lote 4, Edif\u00edcio Maria L\u00facia 302' },
  'RQB0777': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-asa-norte-brasilia-df-shtn-trecho-2-lote-3-1404953', region: 'ASA NORTE', address: 'Setor SHTN Trecho 2 Lote 3 304, Bloco B' },
  'RQB0778': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-setor-industrial-taguatinga-df-qi-3-1404969', region: 'TAGUATINGA', address: 'Quadra QI 3, Setor Industrial' },
  'RQB0780': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-4-quartos-venda-grande-colorado-sobradinho-df-condomnio-vivendas-bela-vista-1406738', region: 'SOBRADINHO', address: 'Rodovia DF-150 Conjunto B 28' },
  'RQB0782': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-sudoeste-brasilia-df-qmsw-5-lote-6-1408551', region: 'SUDOESTE', address: 'Quadra QMSW 5 Lote 6' },
  'RQB0783': { url: 'https://www.dfimoveis.com.br/imovel/casa-4-quartos-venda-guara-i-guara-df-qe-3-conjunto-i-1407941', region: 'GUAR\u00c1 I E II', address: 'Quadra QE 3 Conjunto I' },
  'RQB0784': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-riacho-fundo-riacho-fundo-df-cln-7-bloco-f-1407961', region: 'RIACHO FUNDO', address: 'Quadra CLN 7 Bloco F' },
  'RQB0785': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-taguatinga-sul-taguatinga-df-csg-3-1407981', region: 'TAGUATINGA', address: 'Quadra CSG 3' },
  'RQB0786': { url: 'https://www.dfimoveis.com.br/imovel/casa-3-quartos-venda-jardins-mangueiral-brasilia-df-qc-8-rua-f-1408542', region: 'JARDIM BOT\u00c2NICO', address: 'Quadra QC 8 Rua F' },
  'RQB0787': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-3-quartos-venda-norte-aguas-claras-df-rua-12-1408559', region: '\u00c1GUAS CLARAS', address: 'Rua 12, Norte' },
  'RQB0788': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-3-quartos-venda-alto-da-boa-vista-sobradinho-df-rodovia-br-0020-km-125-1413271', region: 'SOBRADINHO', address: 'Rodovia BR-020, Quadra 203, Conjunto 4 18' },
  'RQB0790': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-setor-industrial-taguatinga-df-qi-24-1410766', region: 'TAGUATINGA', address: 'Quadra QI 24' },
  'RQB0793': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-4-quartos-venda-sul-aguas-claras-df-rua-18-1410896', region: '\u00c1GUAS CLARAS', address: 'Rua 18, Sul' },
  'RQB0794': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-3-quartos-venda-vicente-pires-vicente-pires-df-rua-10-1411938', region: 'VICENTE PIRES', address: 'Rua 10, Lote 07 A' },
  'RQB0795': { url: 'https://www.dfimoveis.com.br/imovel/casa-condominio-3-quartos-venda-vicente-pires-vicente-pires-df-rua-10-1411947', region: 'VICENTE PIRES', address: 'Rua 10, Lote 07 C' },
  'RQB0796': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-taguatinga-norte-taguatinga-df-setor-sagoca-lote-2---residencial-esplanada-1413248', region: 'TAGUATINGA', address: 'Setor SAGOCA Lote 2 1603, BLOCO A' },
  'RQB0798': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-sul-aguas-claras-df-rua-22-1414806', region: '\u00c1GUAS CLARAS', address: 'Rua 22, Sul' },
  'RQB0799': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-norte-aguas-claras-df-rua-das-carnaubas-1414774', region: '\u00c1GUAS CLARAS', address: 'Rua das Carna\u00fabas' },
  'RQB0800': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-1-quarto-venda-lago-norte-brasilia-df-ca-11-1415683', region: 'LAGO NORTE', address: 'Quadra CA 11, Setor de Habita\u00e7\u00f5es Individuais Norte' },
  'RQB0801': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-sul-aguas-claras-df-rua-9-1415663', region: '\u00c1GUAS CLARAS', address: 'Rua 9, Sul' },
  'RQB0802': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-norte-aguas-claras-df-rua-13-1415666', region: '\u00c1GUAS CLARAS', address: 'Rua 13, Norte' },
  'RQB0803': { url: 'https://www.dfimoveis.com.br/imovel/apartamento-2-quartos-venda-norte-aguas-claras-df-rua-19-1416098', region: '\u00c1GUAS CLARAS', address: 'Rua 19, Norte' },
  'RQB0804': { url: '', region: '\u00c1GUAS CLARAS', address: 'Setor SCIA Quadra 15 Conjunto 6 12' },
  'RQB0806': { url: '', region: 'ASA NORTE', address: 'SCN Quadra 5 Bloco A Torre Norte Sala 825' },
  'RQB0810': { url: '', region: 'JARDIM BOT\u00c2NICO', address: 'Condom\u00ednio Morada de Deus, Setor Habitacional Individuais Norte' },
};
