import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { Prisma } from '@prisma/client';
import { notifyNewLead } from '@/lib/telegram';
import { rateLimit } from '@/lib/rate-limit';
import { assignLeadToUser, type AssignResult } from '@/lib/lead-queue';

/**
 * PUBLIC endpoint — no auth required.
 * Receives a lead submission from a landing page form.
 * Creates a Client record and assigns it via the lead queue.
 *
 * SAFETY GUARANTEES:
 * 1. Client creation + dedup check run inside a Serializable transaction
 *    to prevent race-condition duplicates.
 * 2. Email has a partial UNIQUE constraint (WHERE email IS NOT NULL) at DB level.
 * 3. Queue assignment has its own Serializable transaction + idempotency cache.
 * 4. Existing clients get their phone/email updated with newest data.
 * 5. Hero mini-form .temp emails are rejected server-side.
 */
export async function POST(request: NextRequest) {
  // Rate limit: 5 submissions per minute per IP
  const rateLimitResult = rateLimit(request, { maxRequests: 5, windowSeconds: 60, keyPrefix: 'public-lead' });
  if (rateLimitResult) return rateLimitResult;

  try {
    const body = await request.json();
    const { name, phone, email, slug, customAnswers, utmSource, utmMedium, utmCampaign, utmContent, utmTerm, metaEventId } = body;

    // ── Validate slug format ──
    if (slug && !/^[a-z0-9-]{1,100}$/.test(slug)) {
      return NextResponse.json({ error: 'Dados inválidos.' }, { status: 400 });
    }

    // ── Validate required fields ──
    if (!name || typeof name !== 'string' || name.trim().length < 2) {
      return NextResponse.json({ error: 'Nome completo é obrigatório (mínimo 2 caracteres).' }, { status: 400 });
    }
    if (name.trim().length > 200) {
      return NextResponse.json({ error: 'Nome muito longo.' }, { status: 400 });
    }

    const cleanPhone = (phone || '').replace(/\D/g, '');
    // Phone is now optional on landing pages — if provided, validate format
    if (cleanPhone.length > 0 && cleanPhone.length < 10) {
      return NextResponse.json({ error: 'Telefone inválido. Informe DDD + número (mínimo 10 dígitos) ou deixe em branco.' }, { status: 400 });
    }
    if (cleanPhone.length > 15) {
      return NextResponse.json({ error: 'Telefone inválido.' }, { status: 400 });
    }

    const cleanEmail = (email || '').trim().toLowerCase();
    if (!cleanEmail || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleanEmail)) {
      return NextResponse.json({ error: 'E-mail é obrigatório e deve ser válido.' }, { status: 400 });
    }
    if (cleanEmail.length > 254) {
      return NextResponse.json({ error: 'E-mail inválido.' }, { status: 400 });
    }
    // REJECT fake .temp emails generated by hero mini-form workaround
    if (cleanEmail.endsWith('@cadastro.temp')) {
      return NextResponse.json({ error: 'E-mail é obrigatório e deve ser válido.' }, { status: 400 });
    }

    // ── Find enterprise by slug ──
    let enterpriseId: string | null = null;
    let enterpriseName: string | null = null;
    let enterpriseRegion: string | null = null;

    if (slug) {
      const enterprise = await db.enterprise.findUnique({
        where: { slug },
        select: { id: true, name: true, region: true },
      });
      if (enterprise) {
        enterpriseId = enterprise.id;
        enterpriseName = enterprise.name;
        enterpriseRegion = enterprise.region;
      }
    }

    // ── Check for existing client (match by email OR phone if provided) ──
    const existingWhere: Prisma.ClientWhereInput[] = [{ email: cleanEmail }];
    if (cleanPhone.length >= 10) {
      existingWhere.push({ phone: cleanPhone });
    }
    const existingClient = await db.client.findFirst({
      where: { OR: existingWhere },
      select: { id: true, name: true, stage: true, enterpriseId: true, phone: true, email: true },
    });

    if (existingClient) {
      // Create interaction recording the repeat contact
      await db.interaction.create({
        data: {
          clientId: existingClient.id,
          description: `[Landing Page] Novo cadastro${enterpriseName ? ` — ${enterpriseName}` : ''}${slug ? ` (slug: ${slug})` : ''}`,
        },
      });

      // CRITICAL FIX: Even for existing clients, still assign via queue
      // so the lead reaches the next available agent.
      // This was previously returning assignedUser: null for existing clients,
      // meaning repeat leads had NO queue assignment.
      let assignedUser: AssignResult | null = null;
      try {
        assignedUser = await assignLeadToUser({
          leadId: existingClient.id,
          source: slug ? `landing_form:${slug}` : 'landing_form',
        });
      } catch (err) {
        console.error('[Public Lead] Falha na atribuição de fila (lead existente):', err);
      }

      // Send Telegram notification for repeat lead
      // FIX: include assignedUserName so the agent knows it's their turn
      if (assignedUser?.assigned && assignedUser.userId) {
        db.user.findUnique({
          where: { id: assignedUser.userId },
          select: { telegramChatId: true },
        }).then((notifyUser) => {
          if (notifyUser?.telegramChatId) {
            notifyNewLead(notifyUser.telegramChatId, {
              leadName: existingClient.name,
              leadPhone: existingClient.phone || '',
              leadEmail: existingClient.email || '',
              enterpriseName,
              utmCampaign: typeof utmCampaign === 'string' ? utmCampaign : null,
              utmSource: typeof utmSource === 'string' ? utmSource : null,
              slug: slug || undefined,
              assignedUserName: assignedUser.userName,
              customAnswers: undefined,
            }).catch((err) => console.warn('[Public Lead] Falha na notificação (lead existente):', err));
          } else {
            // FIX: Log when assigned user has no Telegram configured — admin should know
            console.warn(`[Public Lead] Usuário ${assignedUser.userName} (${assignedUser.userId}) atribuído mas sem Telegram configurado. Lead ${existingClient.id} sem notificação.`);
          }
        }).catch(() => { /* non-critical: DB lookup failed, lead is still saved */ });
      } else {
        // FIX: Log when no queue was available — admin should know leads are coming without notification
        console.warn(`[Public Lead] Lead existente ${existingClient.id} sem fila disponível. Nenhuma notificação enviada.`);
      }

      return NextResponse.json({
        success: true,
        isExisting: true,
        clientId: existingClient.id,
        clientName: existingClient.name,
        assignedUser: assignedUser?.assigned ? {
          userId: assignedUser.userId,
          userName: assignedUser.userName,
          userPhone: assignedUser.userPhone,
        } : null,
      });
    }

    // ── Helper: send Telegram notification (fire-and-forget) ──
    const sendNotification = (userId: string, leadData: Parameters<typeof notifyNewLead>[1], clientName: string) => {
      db.user.findUnique({
        where: { id: userId },
        select: { telegramChatId: true, name: true },
      }).then((user) => {
        if (user?.telegramChatId) {
          notifyNewLead(user.telegramChatId, leadData).catch((err) =>
            console.warn(`[Public Lead] Falha na notificação Telegram para ${user.name}:`, err)
          );
        } else {
          console.warn(`[Public Lead] Usuário ${user?.name || userId} sem Telegram configurado. Lead ${clientName} sem notificação push.`);
        }
      }).catch(() => { /* non-critical */ });
    };

    // ── Build custom answers text ──
    let customAnswersText = '';
    if (customAnswers && typeof customAnswers === 'object' && Object.keys(customAnswers).length > 0) {
      const lines = Object.entries(customAnswers)
        .filter(([, v]) => v !== undefined && v !== null && String(v).trim() !== '')
        .slice(0, 20)
        .map(([k, v]) => `  • ${String(k).slice(0, 50)}: ${String(v).slice(0, 500)}`);
      if (lines.length > 0) {
        customAnswersText = '\n\nRespostas do formulário:\n' + lines.join('\n');
      }
    }

    // ════════════════════════════════════════════════════════════
    // CRITICAL FIX: Wrap dedup check + client creation in a
    // Serializable transaction to prevent race-condition duplicates.
    // ════════════════════════════════════════════════════════════
    interface ClientResult {
      id: string; name: string; phone: string | null; email: string | null;
    }
    interface ClientOutcome { client: ClientResult; isNew: boolean }

    const getClientOrCreate = async (): Promise<ClientOutcome> => {
      const MAX_RETRIES = 3;
      let lastError: unknown;

      for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
        try {
          return await db.$transaction(async (tx) => {
            // Check for existing client (email OR phone)
            const existingWhere: Prisma.ClientWhereInput[] = [{ email: cleanEmail }];
            if (cleanPhone.length >= 10) {
              existingWhere.push({ phone: cleanPhone });
            }

            const existing = await tx.client.findFirst({
              where: { OR: existingWhere },
              select: { id: true, name: true, phone: true, email: true },
            });

            if (existing) {
              // ── UPDATE: sync newest phone/email if provided ──
              const updates: Prisma.ClientUpdateManyMutationInput = {
                lastInteractionAt: new Date(),
              };
              // Update phone if new one provided and different
              if (cleanPhone.length >= 10 && existing.phone !== cleanPhone) {
                updates.phone = cleanPhone;
              }
              // Email matched — no update needed for email

              await tx.client.update({
                where: { id: existing.id },
                data: updates,
              });

              return {
                client: existing,
                isNew: false,
              };
            }

            // ── NEW CLIENT: find a user for createdBy (required FK) ──
            const firstUser = await tx.user.findFirst({
              select: { id: true },
              orderBy: { createdAt: 'asc' },
            });
            if (!firstUser) {
              throw new Error('NO_USER');
            }

            // Create client
            const newClient = await tx.client.create({
              data: {
                name: name.trim(),
                phone: cleanPhone.length >= 10 ? cleanPhone : null,
                email: cleanEmail || null,
                region: enterpriseRegion,
                enterprise: enterpriseName || undefined,
                enterpriseId: enterpriseId || undefined,
                stage: 'LEAD',
                createdBy: firstUser.id,
                utmSource: typeof utmSource === 'string' ? utmSource.slice(0, 200) : undefined,
                utmMedium: typeof utmMedium === 'string' ? utmMedium.slice(0, 100) : undefined,
                utmCampaign: typeof utmCampaign === 'string' ? utmCampaign.slice(0, 200) : undefined,
                utmContent: typeof utmContent === 'string' ? utmContent.slice(0, 200) : undefined,
                utmTerm: typeof utmTerm === 'string' ? utmTerm.slice(0, 200) : undefined,
                notes: `[Landing Page] Cadastro realizado via formulário${enterpriseName ? ` — ${enterpriseName}` : ''}${slug ? `\nSlug: ${slug}` : ''}${utmCampaign ? `\nCampanha: ${utmCampaign}` : ''}${customAnswersText}`,
              },
            });

            return {
              client: { id: newClient.id, name: newClient.name, phone: newClient.phone, email: newClient.email },
              isNew: true,
            };
          }, {
            isolationLevel: 'Serializable',
            timeout: 15000,
          });
        } catch (error) {
          lastError = error;
          if (error instanceof Prisma.PrismaClientKnownRequestError) {
            // P2002 = unique constraint violation (email already exists)
            if (error.code === 'P2002') {
              // Retry — on next iteration, findFirst will find the existing client
              if (attempt < MAX_RETRIES - 1) {
                await new Promise((r) => setTimeout(r, 50 * (attempt + 1)));
                continue;
              }
              // Last attempt: do a plain findFirst outside transaction
              const existing = await db.client.findFirst({
                where: { email: cleanEmail },
                select: { id: true, name: true, phone: true, email: true },
              });
              if (existing) {
                return { client: existing, isNew: false };
              }
            }
          }
          // Custom error: no user in system
          if (error instanceof Error && error.message === 'NO_USER') {
            throw error;
          }
          // Serialization failure — retry
          const isSerializationError =
            error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2028';
          if (isSerializationError && attempt < MAX_RETRIES - 1) {
            await new Promise((r) => setTimeout(r, 50 * (attempt + 1)));
            continue;
          }
          throw error;
        }
      }
      throw lastError;
    };

    // ── Execute atomic client lookup/creation ──
    let clientResult: Awaited<ReturnType<typeof getClientOrCreate>>;
    try {
      clientResult = await getClientOrCreate();
    } catch (error) {
      if (error instanceof Error && error.message === 'NO_USER') {
        console.error('[Public Lead] Nenhum usuário encontrado no sistema. Lead perdido.');
        return NextResponse.json({ error: 'Sistema não configurado: nenhum usuário cadastrado.' }, { status: 500 });
      }
      throw error;
    }

    const { client, isNew } = clientResult;

    // ── Create interaction record ──
    await db.interaction.create({
      data: {
        name: name.trim(),
        phone: cleanPhone.length >= 10 ? cleanPhone : null,
        email: cleanEmail || null,
        region: enterpriseRegion,
        enterprise: enterpriseName || undefined,
        enterpriseId: enterpriseId || undefined,
        stage: 'LEAD',
        createdBy: createdByUserId,
        utmSource: typeof utmSource === 'string' ? utmSource.slice(0, 200) : undefined,
        utmMedium: typeof utmMedium === 'string' ? utmMedium.slice(0, 100) : undefined,
        utmCampaign: typeof utmCampaign === 'string' ? utmCampaign.slice(0, 200) : undefined,
        utmContent: typeof utmContent === 'string' ? utmContent.slice(0, 200) : undefined,
        utmTerm: typeof utmTerm === 'string' ? utmTerm.slice(0, 200) : undefined,
        notes: `[Landing Page] Cadastro realizado via formulário${enterpriseName ? ` — ${enterpriseName}` : ''}${slug ? `\nSlug: ${slug}` : ''}${utmCampaign ? `\nCampanha: ${utmCampaign}` : ''}${customAnswersText}`,
      },
    });

    // ── Assign via lead queue ──
    let assignedUser: AssignResult | null = null;
    try {
      assignedUser = await assignLeadToUser({
        leadId: client.id,
        source: slug ? `landing_form:${slug}` : 'landing_form',
      });
      if (assignedUser?.assigned && assignedUser.userId && isNew) {
        // Update createdBy to the queue-assigned user (only for new clients)
        await db.client.update({
          where: { id: client.id },
          data: { createdBy: assignedUser.userId },
        }).catch(() => { /* non-critical */ });
      }
    } catch (err) {
      console.error(`[Public Lead] Falha na atribuição de fila (${isNew ? 'lead novo' : 'lead existente'}):`, err);
    }

    // ── Send Telegram notification ──
    if (assignedUser?.assigned && assignedUser.userId) {
      sendNotification(assignedUser.userId, {
        leadName: client.name,
        leadPhone: client.phone || '',
        leadEmail: client.email || '',
        enterpriseName,
        utmCampaign: typeof utmCampaign === 'string' ? utmCampaign : null,
        utmSource: typeof utmSource === 'string' ? utmSource : null,
        slug: slug || undefined,
        assignedUserName: assignedUser.userName,
        customAnswers: (customAnswers && typeof customAnswers === 'object')
          ? Object.fromEntries(
              Object.entries(customAnswers).filter(([, v]) => v !== undefined && v !== null && String(v).trim() !== ''),
            ) as Record<string, string>
          : undefined,
      }, client.name);
    } else {
      console.warn(`[Public Lead] Lead ${client.id} (${client.name}) sem fila disponível. Nenhuma notificação enviada.`);
    }

    // ── Fire Meta CAPI event ──
    fireMetaCAPI();

    return NextResponse.json({
      success: true,
      isExisting: !isNew,
      clientId: client.id,
      clientName: client.name,
      assignedUser: assignedUser?.assigned ? {
        userId: assignedUser.userId,
        userName: assignedUser.userName,
        userPhone: assignedUser.userPhone,
      } : null,
    });
  } catch (error) {
    console.error('[Public Lead] Erro:', error);
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      return NextResponse.json({ error: 'Cadastro já realizado com esses dados.' }, { status: 409 });
    }
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2003') {
      return NextResponse.json({ error: 'Erro de configuração: nenhum usuário cadastrado no sistema.' }, { status: 500 });
    }
    return NextResponse.json({ error: 'Erro interno do servidor.' }, { status: 500 });
  }
}
